# Methods

## salmonMSE operating model {#sec:om}

salmonMSE is a stochastic, forward projecting model that incorporate the full life-cycle of salmon.
The abundance of brood year by age and time is accounted in an age-structured matrix, which can accommodate single brood-year and multiple brood-year returns. **Details are to be presented in a separate document TBD**, but we briefly describe important features for the case study here.

An individual operating model encompasses biological parameters controlling juvenile natural survival and proportion maturing by age class in the marine life stage.

A single brood year can be sub-divided by natural-origin and hatchery-origin fish.
For hatchery-origin fish, release strategies represent groups of fish that can be reared in different environments (e.g., seapens vs. freshwater hatchery) and released at different sizes, weights, time within season. These strategies can impact mortality and maturity.
For natural-origin fish, different life history strategies represent groups of fish that outmigrate from freshwater habitat at different times and seasons [@sorel2023; @zimmerman2015], which can impact marine survival [@brown2025].
Each group of fish are accounted for separately in the age-structured matrix.

Juvenile, preterminal harvest occurs in the first half of the year and is specified by a harvest rate, vulnerability schedule which controls the proportion of the harvest rate experience by each age class, and presence/absence of mark-selective fishing.
Maturity can occur in the mid-point of the annual time step; the proportion of immature individuals then experience natural mortality in the second half of the year and then advance to the next age class.

Mature individuals comprise the return which are vulnerable to the terminal marine fishery (the management levers are identical to the preterminal fishery).

The in-river return includes individuals not caught in the terminal marine fishery. Broodtake removals from a return year are determined by a release target (number of releases), and target brood numbers are identified by fecundity, and survival of brood and eggs in the hatchery. Selective brood with respect to parental origin by identifying the target proportion of natural-origin brood (pNOB), assuming a mark rate of 1. It is assumed brood is non-selective with respect to age. Brood numbers can also be limited by return size.

Additional hatchery-origin fish can be removed from the spawning grounds, ostensibly as part of an in-river fishery to limit spawning of hatchery-origin fish in the natural environment.

The escapement from the in-river fishery spawn in the natural environment. Survival through freshwater life stages, e.g., pre-spawn mortality of adults, egg incubation, emergence-fry, fry-smolt, can be density-dependent or density-independent, and stochastic through time.
The outmigrating juveniles enter the marine environment in the following year. 
Natural-origin juveniles are 
It is possible that the releases (hatchery-origin releases) do not reach the target if there is insufficient brood due to low returns or constraint from the specified brood rule).

From an initial juvenile abundance at age, an operating model can be projected forward in time to understand the effect of a particular management strategy on the long-term dynamics of the population.

## Case study 

This paper uses Chinook salmon in the Sarita River as a case study to illustrate how salmonMSE can be used to identify objectives, identify management levers, identify management options, and evaluate performance of the management options relative to objectives.
The Sarita River drains into Barkley Sound in southwest Vancouver Island, BC. 
Portions of the river are heavily degraded which can limit access to spawning habitat in dry autumns and egg survival due to sedimentation and scouring. 
The Chinook salmon population is enhanced by hatchery production from the Nitinat Hatchery.
Since 2016, the Huu-ay-aht First Nation (HFN) has conducted significant monitoring of Chinook salmon in the Sarita River, including assessment of juvenile outmigration and adult returns.
HFN also has a mark-selective in-river fishery for Sarita River Chinook enabled by Maa-nulth Treaty provisions.

### Management objectives

The management objectives proposed for Sarita Chinook are to:

1. Increase number of spawners. 
2. Increase "wildness" of the population, i.e., decrease hatchery influence. Currently, approximately 85% of spawners are hatchery-origin [@brown2025]. 
3. Evaluate the potential for an in-river mark-selective fishery for Huuy-ay-aht First Nations.

To demonstrate how decision support tools such as salmonMSE can support decision-making, broad management objectives should be operationalized into quantitative outcomes. 
The corresponding performance outcomes are:

1. Ensure natural spawners exceed 1300 (1300 spawners was identified as a benchmark for equilibrium spawners in @brown2025)
2. Ensure PNI exceeds 0.5 (the threshold to reach integrated-transition status where natural-origin fish predominates; @withler2018)
3. Maximize catch in the in-river fishery

### Management levers

Five management levers have been identified to achieve the specified objectives:

1. Freshwater stewardship (FS) to improve freshwater habitat to increase egg survival and production of natural-origin smolts with better marine survival.
2. Mass-marking (MM) of hatchery-origin juveniles to facilitate selective broodtake and mark-selective fishing
3. In-river (IR) fishery 
4. Selective broodtake, i.e., preferential use of natural-origin fish as broodstock, based on pNOB targets
5. Enabling mark-selective fishing for the marine terminal fishery (MSF_T)

<!-- Note that the preterminal fishing exploitation rate was considered out of scope for decision-making. -->

The marginal value of the various levers can be evaluated through three management questions:

1. To what extent would freshwater stewardship (FS) enhance our ability to meet objectives?
2. Is it possible to reach objectives without mass-marking and selective broodtake?
3. How important are mark-selective fisheries to achieving the objectives?

### Modeling scenarios

A factorial combination of scenarios were simulated based on different actions for management levers:

1. **Freshwater stewardship**: mean freshwater survival of 10, 15, and 20 percent. 
2. **Mass-marking**: mark rate of 1 or zero of hatchery-origin fish.
3. **In-river fishery**: exploitation rate of zero, 0.25, and 0.75 with fixed total escapement of 1300. The fishery is mark-selective if mass-marking is present, and non-selective otherwise.
4. **Selective broodtake**: pNOB target of either 1 or 0.5 if mass-marking is present. Otherwise brood is non-selective.
5. **Mark-selective terminal fishing**: Whether the terminal marine fishery is mark-selective of not.

Further details of the population model and management options are provided in Appendix \@ref(app:OM). 
Freshwater survival is modeled as a stochastic time series over time to reflect inter-annual variability in environmental conditions (Figure \@ref(fig:fry-surv)).
The in-river fishery and broodtake operating under specific algorithms described in Appendix Sections \@ref(app:brood) and \@ref(app:irf), respectively.

### Performance outcomes

To evaluate and compare alternative management options, five primary performance metrics were calculated to describe outcomes at the end of the 30-year projection:

- **PNI** proportion natural influence to determine the extent of hatchery influence to the spawning population
- **Natural spawners** to determine the overall size of the spawning population
- **P_PNI_50** probability that PNI exceeds 0.5
- **P_NS_1300** probability that natural spawners exceed 1300
- **IR Catch** catch from in-river fishery

Ancillary performance metrics reporting state variables and other life stages may complement primary performance metrics to understand the system dynamics:

- **IR Return**, the in-river return of mature fish after vulnerability to the terminal fishery
- **Brood** number of natural and hatchery origin brood used to validate whether the modeled size of the hatchery based on release targets is similar in size to the current hatchery
- **Egg** production in the natural environment from NOS and HOS
- **Releases** hatchery production, summed across release strategies (units of hundreds of thousands of juveniles) to determine if hatchery targets are achieved in the long-term
- **pNOBeff** the "effective pNOB" to validate whether the pNOB target can be achieved. The effective pNOB is weighted by age class fecundity while the nominal pNOB used in the target is calculated from abundance only.
- **pHOSeff** proportion of effective hatchery spawners used to calculate **PNI**

To support further policy objectives from the Wild Salmon Policy and the Precautionary Approach Framework, the following metrics are reported:

- **pWILD** proportion wild spawners
- **P_250_NOS** probability that natural origin spawners exceed the lower benchmark of 250 [@brown2025]
- **P_476_NOS** probability that natural origin spawners exceed the upper benchmark of 476 [@brown2025]
- **P_250** probability that total spawners exceed the lower benchmark of 250
- **P_476** probability that total spawners exceed the upper benchmark of 476

A summary table is provided in Table \@ref(tab:pm).
For non-probability metrics, the median values across simulations are reported. A summary is provided in Table \@ref(tab:pm).

\newpage

```{r pm, results="as-is"}
pm <- readr::read_csv(here::here("tables/pm.csv"))

flextable(pm) %>%
  set_caption(
    "Definitions of performance metrics, either a median or probability calculated across simulations for each management option. Primary performance metrics are intended to describe core outcomes to meet Sarita Chinook objectives, while ancillary metrics are intended to aid understanding of the system dynamics support broader policy objectives."
  ) %>%
  width(j = 1, width = 1) %>% 
  width(j = 2, width = 3) %>%
  width(j = 3, width = 1.5)
```

