---
english_title: |
  Tentative Title: Development of salmonMSE as a decision support tool for Sarita River Chinook salmon (*Oncorhynchus tshawytscha*), February 25, 2026 draft
french_title: |
  Titre ici (*Nom latin de l'espèce*)

author: |
  Quang C. Huynh^1^ and others TBD

english_address: |
  ^1^Blue Matter Science\
french_address: |
  ^1^Blue Matter Science\

english_region: "Pacific Region"
french_region: "Région du Pacifique"

year: "2026"
report_number: "000"

english_preamble_pages: "iv"
french_preamble_pages: "iv"
english_content_pages: "999"
french_content_pages: "999"
english_doi: "###"
french_doi: "###"
english_isbn: "###"
french_isbn: "###"
english_cat_no: "###"
french_cat_no: "###"

abstract: |
  Here is the abstract text. It must not be more than 1/2 page (roughly 400 words).

  Start new paragraphs after a blank line and with 2 spaces indent.

output:
 csasdown::techreport_docx:
   french: false
knit: (function(input, ...) csasdown::render())
bibliography: bib/refs.bib
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
opts_chunk$set(
  #  cache = TRUE, # cache all chunks?
  #  autodep = TRUE, # try to guess which chunks depend on which in cache?
  #fig.width = 6, # 'internal' plotting figure width (inches)
  out.height = "100%"
  #out.width = "100%" # output plotting width; adjust here or by chunk if desired
  #fig.asp = 1 / 1.618, # golden ratio; adjust here or by chunk if desired
  #dpi = 200 # adjust to taste; larger = higher resolution but larger file size
)
```

```{r load-libraries-csasdown}
library(csasdown) # for new_appendix(), current_appendix(), appendix_table_caption()
library(flextable) # recommended package for adding tables
```

```{r table-settings}
# recommended table settings to match CSAS table style and accessibility standards
flextable::set_flextable_defaults(
  font.size = 10,
  padding.left = 3, 
  padding.right = 3, 
  padding.top = 1, 
  padding.bottom = 1,
  na_str = "-",
  theme_fun = "theme_booktabs"
)
```

```{r load-libraries-user}
library(dplyr) # used in examples in template example
library(ggplot2) # used in examples in template example
# add more packages here as needed
library(magick)

get_asp <- function(x) {
  info <- magick::image_info(magick::image_read(x))
  info$height / info$width
}
```
